### ISSUE TITLE
please include LICENSE files in repo + published crates

### ISSUE THREAD

**Issue by decathorpe** [niklasmohrin/clircle#10]
Both the MIT and Apache-2.0 licenses require that redistributed sources contain a copy of the license terms. The lack of license text is technically a violation of the terms, which is a problem for both crates.io and Linux Distributions which redistribute this crate.

You can look at popular crates like [serde_json](https://github.com/serde-rs/json) how this is usually handled for projects that are "MIT OR Apache-2.0" dual-licensed.

**Comment by niklasmohrin** [comment]
Good catch, I released version 0.4.0 to include the files :)

**Comment by niklasmohrin** [comment]
@sharkdp Pinging you in case you want to also issue a release of bat with this new version.

**Comment by decathorpe** [comment]
Thanks for the quick fix!

**Comment by sharkdp** [comment]
Updated in `bat`, thanks for the ping https://github.com/sharkdp/bat/commit/8676bbf97f2832ad2231e102ca9c9b7b72267fda
