### ISSUE TITLE
RFE: port to nix 0.29

### ISSUE THREAD

**Issue by michel-slm** [niklasmohrin/clircle#15]
`clircle` 0.4.0+ mostly builds fine with Nix 0.27 and above in Fedora - we're still on 0.4.0 because `bat` has not been ported to use 0.5.0 yet

see https://koji.fedoraproject.org/koji/packageinfo?packageID=34719

The only change is to adjust for Nix >= 0.27 returning OwnedFd instead of raw pointers for some operations:
https://github.com/nix-rust/nix/blob/master/CHANGELOG.md#changed-2

which we currently work around:
https://src.fedoraproject.org/rpms/rust-clircle/pull-request/1#request_diff

This is obviously not the cleanest solution - ideally clircle is refactored to use OwnedFd instead of integers as appropriate - but we're in the middle of bootstrapping packages for EPEL 10 (the add-on extra packages repo for Enterprise Linux 10 distributions) and would rather not have to build and support older Nix crates there.

If an upcoming clircle release can be ported to use the latest Nix, we can try and get `bat` to use it and that way it will be worth it to upgrade to the latest clircle too.

**Comment by decathorpe** [comment]
Note that the initial patch we made was a bit broken - it caused the files to be closed before they were used. A followup change avoids that issue, though it looks like clircle will need some minor code changes to adapt to nix now returning OwnedFds.

This patch now works without test failures: https://src.fedoraproject.org/rpms/rust-clircle/blob/rawhide/f/clircle-handle_ownedfd_for_nix_ge_0_27.diff

**Comment by decathorpe** [comment]
Thank you! 🚀

**Comment by niklasmohrin** [comment]
Of course, thanks for reporting :) Release and PR to bat will probably come out later today

**Comment by niklasmohrin** [comment]
See https://github.com/sharkdp/bat/pull/3113
